name: intracs_application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  intracs_entities:
    path: ../entities

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.19.5
