name: intracs_visualization
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  intracs_gateways:
    path: ../../adapter/gateways
  intracs_presenters:
    path: ../../adapter/presenters
  intracs_controllers:
    path: ../../adapter/controllers

  intracs_application:
    path: ../../inner/application
  intracs_entities:
    path: ../../inner/entities

  intracs_devices:
    path: ../devices
  intracs_datasources:
    path: ../datasources